server:
  port: 8001
spring:
  cloud: 
    config:
      server:      
        git:
#          default-label: dev
          default-label: eureka #trabajamos con la rama eureka
          uri: https://github.com/luishz2009/Microservicios_Usuarios.git
          search-paths: config-data
  application:
    name: config-service