server:
  port: 8001
spring:
  cloud: 
    config:
      server:      
        git:
          default-label: dev
          uri: https://github.com/luishz2009/Microservicios_Usuarios.git
          search-paths: config-data
  application:
    name: config-service