server:
  port: 8001
spring:
  cloud: 
    config:
      server:      
        git:
          default-label: gateway
          uri: https://github.com/luishz2009/Microservicios_Usuarios.git
          search-paths: config-data
  application:
    name: config-service
    #Primero trabajamos con la rama dev, luego con eureka y ahora con la rama multiple-instances
    #Después de multiple-instances vamos a trabajar con la rama geteway